// Catálogo de productos por área
// IDs de área usados en la app:
// "BFS_PGV_321", "VIDRIO", "PVC_PP", "BFS_PPV_312", "HEMODIALISIS", "BFS_PGV_305", "DIVISION_PLASTICOS"

export type ItemCatalogo = {
  id: string;          // interno (puedes usar "AREA-CODIGO")
  codigo: string;      // código del producto en tu tabla
  nombre: string;
  vol?: string;        // ej: "1000 ml", "2 ml", "10 L"
  envase?: string;     // texto libre de presentación/envase
};

export type CatalogoPorArea = Record<string, ItemCatalogo[]>;

export const CATALOGO_POR_AREA: CatalogoPorArea = {
  BFS_PGV_321: [
    { id: "BFS_PGV_321-01", codigo: "01", nombre: "Solución Ringer Normal", vol: "1000 ml", envase: "Frasco infusor de PEBD Flex" },
    { id: "BFS_PGV_321-02", codigo: "02", nombre: "Solución Fisiológica 0,9%", vol: "1000 ml", envase: "Frasco infusor de PEBD con sistema de cierre twist off" },
    { id: "BFS_PGV_321-03", codigo: "03", nombre: "Solución de Glucosa isotónica al 5%", vol: "1000 ml", envase: "Frasco infusor de PEBD Flex" },
    { id: "BFS_PGV_321-04", codigo: "04", nombre: "Solución Glucosa Hipertónica al 10%", vol: "1000 ml", envase: "Frasco infusor de PEBD Flex" },
    { id: "BFS_PGV_321-05", codigo: "05", nombre: "Solución para Diálisis Peritoneal con glucosa al 1.5% (Diálisis I)", vol: "1000 ml", envase: "Frasco infusor de PEBD Flex" },
    { id: "BFS_PGV_321-06", codigo: "06", nombre: "Solución de Ringer Lactato 'Hartmann'", vol: "1000 ml", envase: "Frasco infusor de PEBD Flex" },
    { id: "BFS_PGV_321-07", codigo: "07", nombre: "Solución para Diálisis Peritoneal con glucosa al 7% (Diálisis II)", vol: "1000 ml", envase: "Frasco infusor de PEBD con sistema de cierre twist off" },
    { id: "BFS_PGV_321-08", codigo: "08", nombre: "Solución Glucosa Clorurada isotónica - Glucosalina", vol: "1000 ml", envase: "Frasco infusor de PEBD Flex" },
    { id: "BFS_PGV_321-09", codigo: "09", nombre: "Solución estéril ABD", vol: "1000 ml", envase: "Frasco infusor de PEBD Flex" },
    { id: "BFS_PGV_321-10", codigo: "10", nombre: "Levofloxacina ABD", vol: "100 ml", envase: "Frasco infusor de PEBD Flex" },
    { id: "BFS_PGV_321-11", codigo: "11", nombre: "Ciprofloxacina", vol: "100 ml", envase: "Frasco infusor de PEBD Flex" },
    { id: "BFS_PGV_321-12", codigo: "12", nombre: "Metronidazol", vol: "100 ml", envase: "Frasco infusor de PEBD Flex" },
    { id: "BFS_PGV_321-13", codigo: "13", nombre: "Fluconazol", vol: "150 ml", envase: "Frasco infusor de PEBD con tapa de PEBD y elastómero TPE" },
    { id: "BFS_PGV_321-14", codigo: "14", nombre: "Solución Fisiológica 0,9%", vol: "1000 ml", envase: "Frasco infusor de PEBD con tapa de PEBD y elastómero TPE" },
    { id: "BFS_PGV_321-15", codigo: "15", nombre: "Solución Fisiológica 0,9%", vol: "1000 ml", envase: "Frasco infusor de PEBD con tapa de PEBD y elastómero TPE" },
    { id: "BFS_PGV_321-16", codigo: "16", nombre: "Solución Ringer Normal", vol: "1000 ml", envase: "Frasco infusor de PEBD Foil cap" },
    { id: "BFS_PGV_321-17", codigo: "17", nombre: "Solución Fisiológica 0,9%", vol: "1000 ml", envase: "Frasco infusor de PEBD con tapa de PEBD y elastómero TPE" },
  ],

  VIDRIO: [
    { id: "VID-01", codigo: "01", nombre: "Cloruro de sodio 20%", vol: "20 ml", envase: "Ampolla incolora vidrio tipo I" },
    { id: "VID-02", codigo: "02", nombre: "Vitamina C ABD", vol: "2 ml", envase: "Ampolla ámbar vidrio tipo I" },
    { id: "VID-03", codigo: "03", nombre: "Bicarbonato de sodio 8%", vol: "20 ml", envase: "Ampolla incolora vidrio tipo I" },
    { id: "VID-04", codigo: "04", nombre: "Dipirona sódica", vol: "2 ml", envase: "Ampolla ámbar vidrio tipo I" },
    { id: "VID-05", codigo: "05", nombre: "Solución de Glucosa al 50%", vol: "20 ml", envase: "Ampolla incolora vidrio tipo I" },
    { id: "VID-07", codigo: "07", nombre: "Quelante ABD", vol: "5 ml", envase: "Ampolla incolora vidrio tipo I" },
    { id: "VID-08", codigo: "08", nombre: "Clorfenamina ABD", vol: "1 ml", envase: "Ampolla ámbar vidrio tipo I" },
    { id: "VID-09", codigo: "09", nombre: "Atracurio ABD", vol: "5 ml", envase: "Ampolla ámbar vidrio tipo I" },
    { id: "VID-10", codigo: "10", nombre: "Cianocobalamina (Vitamina B12)", vol: "1 ml", envase: "Ampolla ámbar vidrio tipo I" },
    { id: "VID-11", codigo: "11", nombre: "Aminofilina ABD", vol: "10 ml", envase: "Ampolla ámbar vidrio tipo I" },
    { id: "VID-12", codigo: "12", nombre: "Propinoxato ABD", vol: "2 ml", envase: "Ampolla incolora vidrio tipo I (SOLO FLEX)" },
    { id: "VID-13", codigo: "13", nombre: "Tramadol ABD", vol: "2 ml", envase: "Ampolla incolora vidrio tipo I (SOLO FLEX)" },
    { id: "VID-14", codigo: "14", nombre: "Doloquerol ABD", vol: "1 ml", envase: "Ampolla ámbar vidrio tipo I" },
    { id: "VID-15", codigo: "15", nombre: "Epifrina ABD", vol: "1 ml", envase: "Ampolla ámbar vidrio tipo I" },
    { id: "VID-16", codigo: "16", nombre: "Norefrina ABD", vol: "4 ml", envase: "Ampolla ámbar vidrio tipo I" },
    { id: "VID-17", codigo: "17", nombre: "Relaxepam ABD", vol: "2 ml", envase: "Ampolla ámbar vidrio tipo I" },
    { id: "VID-19", codigo: "19", nombre: "Bupidrato ABD", vol: "10 ml", envase: "Ampolla incolora vidrio tipo I (SOLO FLEX)" },
    { id: "VID-20", codigo: "20", nombre: "Bupidex ABD", vol: "4 ml", envase: "Ampolla incolora vidrio tipo I (SOLO FLEX)" },
    { id: "VID-21", codigo: "21", nombre: "Morfium ABD", vol: "1 ml", envase: "Ampolla ámbar vidrio tipo I" },
    { id: "VID-22", codigo: "22", nombre: "Dipirona sódica ABD", vol: "4 ml", envase: "Ampolla ámbar vidrio tipo I" },
    { id: "VID-23", codigo: "23", nombre: "Cisatracurio ABD", vol: "5 ml", envase: "Ampolla ámbar vidrio tipo I" },
    { id: "VID-24", codigo: "24", nombre: "Gluconato de calcio al 10%", vol: "10 ml", envase: "Ampolla incolora vidrio tipo I" },
    { id: "VID-25", codigo: "25", nombre: "Fitamin K ABD", vol: "1 ml", envase: "Ampolla ámbar vidrio tipo I" },
    { id: "VID-26", codigo: "26", nombre: "Etamsilato ABD", vol: "2 ml", envase: "Ampolla ámbar vidrio tipo I" },
    { id: "VID-28", codigo: "28", nombre: "Dexa ABD", vol: "1 ml", envase: "Ampolla ámbar vidrio tipo I" },
    { id: "VID-29", codigo: "29", nombre: "Beta ABD", vol: "1 ml", envase: "Ampolla ámbar vidrio tipo I" },
    { id: "VID-30", codigo: "30", nombre: "Gentamicin ABD", vol: "2 ml", envase: "Ampolla ámbar vidrio tipo I" },
    { id: "VID-31", codigo: "31", nombre: "Metopramida ABD", vol: "2 ml", envase: "Ampolla vidrio tipo I" },
    { id: "VID-32", codigo: "32", nombre: "Amikacin ABD", vol: "2 ml", envase: "Ampolla incolora vidrio tipo I" },
    { id: "VID-33", codigo: "33", nombre: "Mucoteina ABD", vol: "3 ml", envase: "Ampolla ámbar vidrio tipo I" },
    { id: "VID-34", codigo: "34", nombre: "Hidramin ABD", vol: "1 ml", envase: "Ampolla ámbar vidrio tipo I" },
    { id: "VID-35", codigo: "35", nombre: "Oxitoc ABD", vol: "1 ml", envase: "Ampolla incolora vidrio tipo I" },
    { id: "VID-36", codigo: "36", nombre: "Brocur ABD", vol: "5 ml", envase: "Ampolla incolora vidrio tipo I" },
    { id: "VID-37", codigo: "37", nombre: "Neuro-ciatic ABD", vol: "1 ml", envase: "Ampolla ámbar vidrio tipo I" },
  ],

  PVC_PP: [
    { id: "PVC-01", codigo: "01", nombre: "Solución Ringer Normal", vol: "1000 ml", envase: "Bolsa infusora de PVC" },
    { id: "PVC-02", codigo: "02", nombre: "Solución Fisiológica 0,9%", vol: "1000 ml", envase: "Bolsa infusora de PVC" },
    { id: "PVC-03", codigo: "03", nombre: "Solución de Glucosa isotónica al 5%", vol: "1000 ml", envase: "Bolsa infusora de PVC" },
    { id: "PVC-04", codigo: "04", nombre: "Metronidazol", vol: "100 ml", envase: "Bolsa infusora de PVC/PP" },
    { id: "PVC-05", codigo: "05", nombre: "Ciprofloxacina", vol: "100 ml", envase: "Bolsa infusora de PVC/PP" },
    { id: "PVC-06", codigo: "06", nombre: "Fluconazol", vol: "100 ml", envase: "Bolsa infusora de PP" },
    { id: "PVC-07", codigo: "07", nombre: "Solución Ringer Normal", vol: "500 ml", envase: "Bolsa infusora de PVC" },
    { id: "PVC-08", codigo: "08", nombre: "Solución Fisiológica 0,9%", vol: "500 ml", envase: "Bolsa infusora de PVC" },
    { id: "PVC-09", codigo: "09", nombre: "Solución de Glucosa isotónica al 5%", vol: "500 ml", envase: "Bolsa infusora de PVC" },
    { id: "PVC-10", codigo: "10", nombre: "Solución Fisiológica 0,9%", vol: "250 ml", envase: "Bolsa infusora de PVC" },
    { id: "PVC-11", codigo: "11", nombre: "Solución Fisiológica 0,9%", vol: "150 ml", envase: "Bolsa infusora de PVC" },
    { id: "PVC-12", codigo: "12", nombre: "DIPA ABD 1,5% CON DEXTROSA", vol: "2000 ml", envase: "Bolsa de PVC + recubrimiento" },
    { id: "PVC-13", codigo: "13", nombre: "DIPA ABD 2,5% CON DEXTROSA", vol: "2000 ml", envase: "Bolsa de PVC + recubrimiento" },
    { id: "PVC-14", codigo: "14", nombre: "DIPA ABD 4,25% CON DEXTROSA", vol: "2000 ml", envase: "Bolsa de PVC + recubrimiento" },
  ],

  BFS_PPV_312: [
    { id: "PPV-01", codigo: "01", nombre: "Agua para inyección ABD", vol: "5 ml", envase: "Ampolla incolora de PEBD" },
    { id: "PPV-02", codigo: "02", nombre: "Agua para inyección ABD", vol: "10 ml", envase: "Ampolla incolora de PEBD" },
    { id: "PPV-03", codigo: "03", nombre: "Cloruro de potasio 20%", vol: "10 ml", envase: "Ampolla incolora de PEBD" },
    { id: "PPV-04", codigo: "04", nombre: "Cloruro de sodio 20%", vol: "10 ml", envase: "Ampolla incolora de PEBD" },
    { id: "PPV-05", codigo: "05", nombre: "Sulfato de magnesio al 10%", vol: "10 ml", envase: "Ampolla incolora de PEBD" },
    { id: "PPV-07", codigo: "07", nombre: "Fentanilo ABD sin conservante", vol: "2 ml", envase: "Ampolla incolora de PEBD" },
    { id: "PPV-08", codigo: "08", nombre: "Midazolam ABD", vol: "3 ml", envase: "Ampolla incolora de PEBD" },
    { id: "PPV-09", codigo: "09", nombre: "Potasse ABD", vol: "10 ml", envase: "Ampolla color rojo de PEBD" },
    { id: "PPV-10", codigo: "10", nombre: "Lidocaín 1% ABD", vol: "5 ml", envase: "Ampolla incolora de PEBD" },
    { id: "PPV-11", codigo: "11", nombre: "Propinoxato ABD", vol: "2 ml", envase: "Ampolla incolora de PEBD" },
    { id: "PPV-12", codigo: "12", nombre: "Tramadol ABD", vol: "2 ml", envase: "Ampolla incolora de PEBD" },
    { id: "PPV-13", codigo: "13", nombre: "Doloquerol ABD", vol: "1 ml", envase: "Ampolla incolora de PEBD" },
    { id: "PPV-14", codigo: "14", nombre: "Epifrina ABD", vol: "1 ml", envase: "Ampolla incolora de PEBD" },
    { id: "PPV-15", codigo: "15", nombre: "Norefrina ABD", vol: "4 ml", envase: "Ampolla incolora de PEBD" },
    { id: "PPV-16", codigo: "16", nombre: "Relaxepam ABD", vol: "2 ml", envase: "Ampolla incolora de PEBD" },
    { id: "PPV-17", codigo: "17", nombre: "Lidocaín 2% ABD", vol: "10 ml", envase: "Ampolla incolora de PEBD" },
    { id: "PPV-18", codigo: "18", nombre: "Bupidrato ABD", vol: "10 ml", envase: "Ampolla incolora de PEBD" },
    { id: "PPV-19", codigo: "19", nombre: "Bupidex ABD", vol: "4 ml", envase: "Ampolla incolora de PEBD" },
    { id: "PPV-20", codigo: "20", nombre: "Morfium ABD", vol: "1 ml", envase: "Ampolla incolora de PEBD" },
    { id: "PPV-21", codigo: "21", nombre: "Cisatracurio ABD", vol: "5 ml", envase: "Ampolla incolora de PEBD" },
    { id: "PPV-22", codigo: "22", nombre: "Fitamin K ABD", vol: "1 ml", envase: "Ampolla incolora de PEBD" },
    { id: "PPV-23", codigo: "23", nombre: "Etamsilato ABD", vol: "2 ml", envase: "Ampolla incolora de PEBD" },
    { id: "PPV-24", codigo: "24", nombre: "Lidocaín 2% ABD", vol: "5 ml", envase: "Ampolla incolora de PEBD" },
    { id: "PPV-25", codigo: "25", nombre: "Fentadose ABD con conservante", vol: "10 ml", envase: "Ampolla incolora de PEBD" },
    { id: "PPV-26", codigo: "26", nombre: "Ondansetrón ABD", vol: "4 ml", envase: "Ampolla incolora de PEBD" },
    { id: "PPV-27", codigo: "27", nombre: "Amikacin ABD", vol: "2 ml", envase: "Ampolla incolora de PEBD" },
    { id: "PPV-28", codigo: "28", nombre: "Metopramida ABD", vol: "2 ml", envase: "Ampolla incolora de PEBD (SOLO FLEX)" },
    { id: "PPV-29", codigo: "29", nombre: "Brocur ABD", vol: "5 ml", envase: "Ampolla incolora de PEBD" },
    { id: "PPV-30", codigo: "30", nombre: "Furosemida ABD", vol: "2 ml", envase: "Ampolla incolora de PEBD (SOLO FLEX)" },
  ],

  HEMODIALISIS: [
    { id: "HEMO-01", codigo: "01", nombre: "Solución R.A. Ácida", vol: "10 L", envase: "Bidón de PEAD" },
    { id: "HEMO-02", codigo: "02", nombre: "Solución R.A. Básica", vol: "10 L", envase: "Bidón de PEAD" },
    { id: "HEMO-03", codigo: "03", nombre: "Solución Ácida ABD", vol: "5 L", envase: "Bidón de PEAD color blanco" },
    { id: "HEMO-04", codigo: "04", nombre: "Solución R.A. Básica", vol: "5 L", envase: "Bidón de PEAD" },
  ],

  BFS_PGV_305: [
    { id: "305-01", codigo: "01", nombre: "Solución de Glucosa isotónica al 5%", vol: "500 ml", envase: "Frasco infusor de PEBD Flex" },
    { id: "305-02", codigo: "02", nombre: "Solución de Ringer Lactato 'Hartmann'", vol: "500 ml", envase: "Frasco infusor de PEBD Flex" },
    { id: "305-03", codigo: "03", nombre: "Solución de Glucosa al 50%", vol: "500 ml", envase: "Frasco infusor de PEBD Flex" },
    { id: "305-04", codigo: "04", nombre: "Solución de Manitol al 20%", vol: "500 ml", envase: "Frasco infusor de PEBD Flex" },
    { id: "305-05", codigo: "05", nombre: "Solución Ringer Normal", vol: "500 ml", envase: "Frasco infusor de PEBD Flex" },
    { id: "305-06", codigo: "06", nombre: "Solución Glucosa Hipertónica al 10%", vol: "500 ml", envase: "Frasco infusor de PEBD Flex" },
    { id: "305-07", codigo: "07", nombre: "Solución Glucosa Clorurada isotónica - Glucosalina", vol: "500 ml", envase: "Frasco infusor de PEBD Flex" },
    { id: "305-08", codigo: "08", nombre: "Solución de Glucosa isotónica al 5%", vol: "1000 ml", envase: "Frasco infusor de PEBD Flex" },
    { id: "305-09", codigo: "09", nombre: "Solución de Ringer Lactato 'Hartmann'", vol: "1000 ml", envase: "Frasco infusor de PEBD Flex" },
    { id: "305-10", codigo: "10", nombre: "Solución Ringer Normal", vol: "1000 ml", envase: "Frasco infusor de PEBD Flex" },
    { id: "305-11", codigo: "11", nombre: "Solución Glucosa Hipertónica al 10%", vol: "1000 ml", envase: "Frasco infusor de PEBD Flex" },
    { id: "305-12", codigo: "12", nombre: "Solución Glucosa Clorurada isotónica - Glucosalina", vol: "1000 ml", envase: "Frasco infusor de PEBD Flex" },
    { id: "305-13", codigo: "13", nombre: "Solución Fisiológica 0,9%", vol: "500 ml", envase: "Frasco infusor de PEBD Flex" },
    { id: "305-14", codigo: "14", nombre: "Solución para Diálisis Peritoneal 1.5% (Diálisis I)", vol: "1000 ml", envase: "Frasco infusor de PEBD Flex" },
    { id: "305-15", codigo: "15", nombre: "Solución para Diálisis Peritoneal 7% (Diálisis II)", vol: "1000 ml", envase: "Frasco con twist off" },
    { id: "305-16", codigo: "16", nombre: "Solución Fisiológica 0,9%", vol: "250 ml", envase: "Frasco infusor de PEBD Flex" },
    { id: "305-17", codigo: "17", nombre: "Solución Fisiológica 0,9%", vol: "150 ml", envase: "Frasco infusor de PEBD Flex" },
    { id: "305-18", codigo: "18", nombre: "Solución Fisiológica 0,9%", vol: "1000 ml", envase: "Frasco infusor de PEBD Flex" },
    { id: "305-19", codigo: "19", nombre: "Solución estéril ABD", vol: "1000 ml", envase: "Frasco infusor de PEBD Flex" },
    { id: "305-20", codigo: "20", nombre: "Hidrata ABD 75 reducida", vol: "250 ml", envase: "Frasco de PEBD Flex" },
    { id: "305-21", codigo: "21", nombre: "Hidrata ABD 90 estándar", vol: "250 ml", envase: "Frasco de PEBD Flex" },
    { id: "305-22", codigo: "22", nombre: "Solución de Glucosa isotónica al 5%", vol: "500 ml", envase: "Frasco infusor de PEBD Foil cap" },
    { id: "305-23", codigo: "23", nombre: "Solución de Ringer Lactato 'Hartmann'", vol: "500 ml", envase: "Frasco infusor de PEBD Foil cap" },
    { id: "305-24", codigo: "24", nombre: "Solución de Glucosa al 50%", vol: "500 ml", envase: "Frasco infusor de PEBD Foil cap" },
    { id: "305-25", codigo: "25", nombre: "Solución de Manitol al 20%", vol: "500 ml", envase: "Frasco infusor de PEBD Foil cap" },
    { id: "305-26", codigo: "26", nombre: "Solución Ringer Normal", vol: "500 ml", envase: "Frasco infusor de PEBD Foil cap" },
    { id: "305-27", codigo: "27", nombre: "Solución Glucosa Hipertónica al 10%", vol: "500 ml", envase: "Frasco infusor de PEBD Foil cap" },
    { id: "305-28", codigo: "28", nombre: "Solución Glucosa Clorurada isotónica - Glucosalina", vol: "500 ml", envase: "Frasco infusor de PEBD Foil cap" },
    { id: "305-29", codigo: "29", nombre: "Solución de Glucosa isotónica al 5%", vol: "1000 ml", envase: "Frasco infusor de PEBD Foil cap" },
    { id: "305-30", codigo: "30", nombre: "Solución de Ringer Lactato 'Hartmann'", vol: "1000 ml", envase: "Frasco infusor de PEBD Foil cap" },
    { id: "305-31", codigo: "31", nombre: "Solución Ringer Normal", vol: "1000 ml", envase: "Frasco infusor de PEBD Foil cap" },
    { id: "305-32", codigo: "32", nombre: "Solución Glucosa Hipertónica al 10%", vol: "1000 ml", envase: "Frasco infusor de PEBD Foil cap" },
    { id: "305-33", codigo: "33", nombre: "Solución Glucosa Clorurada isotónica - Glucosalina", vol: "1000 ml", envase: "Frasco infusor de PEBD Foil cap" },
    { id: "305-34", codigo: "34", nombre: "Solución Fisiológica 0,9%", vol: "500 ml", envase: "Frasco infusor con tapa PEBD + TPE" },
    { id: "305-35", codigo: "35", nombre: "Solución para Diálisis Peritoneal 1.5% (Diálisis I)", vol: "1000 ml", envase: "Frasco infusor de PEBD Foil cap" },
    { id: "305-36", codigo: "36", nombre: "Solución para Diálisis Peritoneal 7% (Diálisis II)", vol: "1000 ml", envase: "Frasco infusor con tapa PEBD + TPE" },
    { id: "305-37", codigo: "37", nombre: "Solución Fisiológica 0,9%", vol: "250 ml", envase: "Frasco infusor con tapa PEBD + TPE" },
    { id: "305-38", codigo: "38", nombre: "Solución Fisiológica 0,9%", vol: "150 ml", envase: "Frasco infusor con tapa PEBD + TPE" },
    { id: "305-39", codigo: "39", nombre: "Solución Fisiológica 0,9%", vol: "1000 ml", envase: "Frasco infusor con tapa PEBD + TPE" },
  ],

  DIVISION_PLASTICOS: [
    { id: "PL-03", codigo: "03", nombre: "Soplado de bidones x 10 litros" },
    { id: "PL-05", codigo: "05", nombre: "INYECTORAS FB 160R - FB 230R" },
    { id: "PL-06", codigo: "06", nombre: "INYECTORAS TAPAS BIDONES ROJAS 10 L" },
    { id: "PL-07", codigo: "07", nombre: "INYECTORAS TAPAS BIDONES AZUL 10 L" },
    { id: "PL-08", codigo: "08", nombre: "REFILADORA" },
  ],
};

// Helper: devuelve lista por área (si no hay, []):
export function getCatalogoPorArea(areaId: string): ItemCatalogo[] {
  return CATALOGO_POR_AREA[areaId] || [];
}
